name: Release

on: [push, pull_request]

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
    - name: Build package
      run: |
        make release
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/